version: '3.8'

services:
  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    volumes:
      - ./public_html:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - blog_network

  oddity:
    container_name: oddity
    build:
      context: .
      dockerfile: oddity/Dockerfile
    restart: unless-stopped
    # env_file:
    #   - .env.dev
    environment:
      TZ: UTC
      BACKUP_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
    volumes:
      - ./blogcontent:/var/www/content
    working_dir: /var/www/content
    entrypoint: ["oddity"]
    command: ["run"]
    networks:
      - blog_network

  # Caddy reverse proxy with PHP support
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/var/log/caddy
      - ./public_html:/var/www/html
    restart: unless-stopped
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge