---
- name: Backup original sshd_config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.backup
    remote_src: yes
  become: yes

- name: Disable SSH socket activation (Ubuntu systemd)
  systemd:
    name: ssh.socket
    enabled: no
    state: stopped
  become: yes
  ignore_errors: yes

- name: Enable SSH service directly
  systemd:
    name: ssh.service
    enabled: yes
  become: yes

- name: Change SSH port to 2222
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
    state: present
  become: yes
  notify: restart sshd

- name: Disable root login over SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: yes
  notify: restart sshd

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: yes
  notify: restart sshd

- name: Disable challenge response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"
    state: present
  become: yes
  notify: restart sshd

- name: Enable PAM for SSH key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    line: "UsePAM yes"
    state: present
  become: yes
  notify: restart sshd

- name: Allow only {{ the_user }} user
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?AllowUsers"
    line: "AllowUsers {{ the_user }}"
    state: present
  become: yes
  notify: restart sshd

- name: Set SSH protocol version 2
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Protocol"
    line: "Protocol 2"
    state: present
  become: yes
  notify: restart sshd

- name: Set max auth tries to 3
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?MaxAuthTries"
    line: "MaxAuthTries 3"
    state: present
  become: yes
  notify: restart sshd

- name: Set client alive interval
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveInterval"
    line: "ClientAliveInterval 300"
    state: present
  become: yes
  notify: restart sshd

- name: Set client alive count max
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveCountMax"
    line: "ClientAliveCountMax 2"
    state: present
  become: yes
  notify: restart sshd

- name: Disable X11 forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
    state: present
  become: yes
  notify: restart sshd

- name: Enable TCP forwarding for agent forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?AllowTcpForwarding"
    line: "AllowTcpForwarding yes"
    state: present
  become: yes
  notify: restart sshd

- name: Enable agent forwarding for development
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?AllowAgentForwarding"
    line: "AllowAgentForwarding yes"
    state: present
  become: yes
  notify: restart sshd

- name: Set maximum sessions to 2
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?MaxSessions"
    line: "MaxSessions 2"
    state: present
  become: yes
  notify: restart sshd

- name: Set verbose logging
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?LogLevel"
    line: "LogLevel VERBOSE"
    state: present
  become: yes
  notify: restart sshd

- name: Disable TCP keep alive
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?TCPKeepAlive"
    line: "TCPKeepAlive no"
    state: present
  become: yes
  notify: restart sshd

- name: Set login grace time
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?LoginGraceTime"
    line: "LoginGraceTime 30"
    state: present
  become: yes
  notify: restart sshd