---
- name: Set swap_file variable
  set_fact:
    swap_file: "{{ swap_file_path }}"

- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  command: "fallocate -l {{ swap_file_size }} {{ swap_file }}"
  when: not swap_file_check.stat.exists
  become: yes

- name: Change swap file permissions
  file:
    path: "{{ swap_file }}"
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Format swap file
  command: "mkswap {{ swap_file }}"
  when: not swap_file_check.stat.exists
  become: yes

- name: Write swap entry in fstab
  mount:
    name: none
    src: "{{ swap_file }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  become: yes

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  become: yes

- name: Set swappiness to 10
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    sysctl_file: /etc/sysctl.d/99-swappiness.conf
  become: yes