[dropbox]
app_key = "ksakna746rkpaar"
app_secret = "le3vfxfaff9l9m9"
redirect_uri = "https://devnetsec.lonefish.net/auth/callback"

[server]
host = "0.0.0.0"
port = 3000
admin_port = 3001
webhook_path = "/webhook"

[sync]
local_base_path = "./sync"
dropbox_folder = "/"

[build]
command = "zola build"
working_directory = "./sync"

[[copy_rules]]
source_pattern = "./sync/public/**/*"
destination = "./output"
recursive = true