---
all:
  children:
    provision:
      hosts:
        provision-server:
          ansible_host: 46.62.170.9
          ansible_port: 22
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/devnetsec_ed25519
          ansible_ssh_extra_args: '-o IdentitiesOnly=yes'
          
    production:
      hosts:
        prod-server:
          ansible_host: 46.62.170.9
          ansible_port: 2222
          ansible_user: kalyan
          ansible_ssh_private_key_file: ~/.ssh/devnetsec_ed25519
          ansible_ssh_extra_args: '-o IdentitiesOnly=yes'